// <auto-generated />
using System;
using Brantas.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Brantas.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BrantasDbContext))]
    [Migration("20260902081450_AddFiscalAnomalies")]
    partial class AddFiscalAnomalies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Brantas.Domain.Entities.Anomaly", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ConfidenceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("DatasetVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValueAtRisk")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ZScore")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.HasIndex("DatasetVersionId", "Severity");

                    b.ToTable("anomalies", (string)null);
                });

            modelBuilder.Entity("Brantas.Domain.Entities.DatasetVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("RecordCount")
                        .HasColumnType("integer");

                    b.Property<int>("Seed")
                        .HasColumnType("integer");

                    b.Property<string>("SourceSet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("dataset_versions", (string)null);
                });

            modelBuilder.Entity("Brantas.Domain.Entities.FiscalAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DatasetVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalAllocation")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DatasetVersionId");

                    b.HasIndex("RegionId", "DatasetVersionId")
                        .IsUnique();

                    b.ToTable("fiscal_allocations", (string)null);
                });

            modelBuilder.Entity("Brantas.Domain.Entities.PovertyIndicator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DatasetVersionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("GdpPerCapita")
                        .HasPrecision(16, 2)
                        .HasColumnType("numeric(16,2)");

                    b.Property<decimal>("HumanDevelopmentIndex")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("PoorPopulation")
                        .HasColumnType("integer");

                    b.Property<decimal>("PovertyDepthIndex")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)");

                    b.Property<decimal>("PovertyRate")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)");

                    b.Property<decimal>("PovertySeverityIndex")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DatasetVersionId");

                    b.HasIndex("RegionId", "DatasetVersionId", "Period")
                        .IsUnique();

                    b.ToTable("poverty_indicators", (string)null);
                });

            modelBuilder.Entity("Brantas.Domain.Entities.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BpsCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("BpsCode", "Level")
                        .IsUnique();

                    b.ToTable("regions", (string)null);
                });

            modelBuilder.Entity("Brantas.Domain.Entities.SyntheticGroundTruth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DatasetVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("ExpectedType")
                        .HasColumnType("integer");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DatasetVersionId");

                    b.HasIndex("RegionId", "DatasetVersionId", "ExpectedType")
                        .IsUnique();

                    b.ToTable("synthetic_ground_truth", (string)null);
                });

            modelBuilder.Entity("Brantas.Domain.Entities.Anomaly", b =>
                {
                    b.HasOne("Brantas.Domain.Entities.DatasetVersion", "DatasetVersion")
                        .WithMany()
                        .HasForeignKey("DatasetVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Brantas.Domain.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatasetVersion");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Brantas.Domain.Entities.FiscalAllocation", b =>
                {
                    b.HasOne("Brantas.Domain.Entities.DatasetVersion", "DatasetVersion")
                        .WithMany()
                        .HasForeignKey("DatasetVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Brantas.Domain.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatasetVersion");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Brantas.Domain.Entities.PovertyIndicator", b =>
                {
                    b.HasOne("Brantas.Domain.Entities.DatasetVersion", "DatasetVersion")
                        .WithMany()
                        .HasForeignKey("DatasetVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Brantas.Domain.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatasetVersion");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Brantas.Domain.Entities.Region", b =>
                {
                    b.HasOne("Brantas.Domain.Entities.Region", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Brantas.Domain.Entities.SyntheticGroundTruth", b =>
                {
                    b.HasOne("Brantas.Domain.Entities.DatasetVersion", "DatasetVersion")
                        .WithMany()
                        .HasForeignKey("DatasetVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Brantas.Domain.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatasetVersion");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Brantas.Domain.Entities.Region", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
