<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Brantas.Application\Brantas.Application.csproj" />
    <ProjectReference Include="..\Brantas.Infrastructure\Brantas.Infrastructure.csproj" />
    <ProjectReference Include="..\Brantas.Analytics\Brantas.Analytics.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.20.1" />
    <PackageReference Include="QuestPDF" Version="2025.7.4" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>c94f6756-4a39-4fdc-a6c8-66fd6f336751</UserSecretsId>
  </PropertyGroup>

</Project>
